---
application: all-of-us-helper
repository: https://github.com/NUARIG/all-of-us-helper.git
deployer: deploy
development:
  server_name: 0.0.0.0:3000
test:
  server_name: 0.0.0.0:3000
staging:
  app_host: vtfsmcdsiapps04.fsm.northwestern.edu
  server_name: all-of-us-helper-staging.cancer.northwestern.edu
  server_alias: all-of-us-helper-staging.cancer.northwestern.edu
  cert_file: /etc/pki/tls/certs/all-of-us-helper-staging_cancer_northwestern_edu_cert.cer
  chain_file: /etc/pki/tls/certs/all-of-us-helper-staging_cancer_northwestern_edu_interm.cer
  key_file: /etc/pki/tls/private/all-of-us-helper-staging_cancer_northwestern_edu.key
production:
  app_host: vfsmnubicapps01.fsm.northwestern.edu
  server_name: all-of-us-helper.cancer.northwestern.edu
  server_alias: all-of-us-helper.cancer.northwestern.edu
  cert_file: /etc/pki/tls/certs/all-of-us-helper_cancer_northwestern_edu_cert.cer
  chain_file: /etc/pki/tls/certs/all-of-us-helper_cancer_northwestern_edu_interm.cer
  key_file: /etc/pki/tls/private/all-of-us-helper_cancer_northwestern_edu.key
support:
  recipients:
    - m-gurley@northwestern.edu
  sender_address: all-of-us-helper@northwestern.edu
redcap:
  development:
    host_url: https://redcap.nubic.northwestern.edu/redcap/api/
    verify_ssl: false
  test:
    host_url: http://redcap.local/redcap/api/
    verify_ssl: false
  staging:
    host_url: https://redcap.nubic.northwestern.edu/redcap/api/
  production:
    host_url: https://redcap.nubic.northwestern.edu/redcap/api/
  dev:
    host_url: https://redcap.nubic.northwestern.edu/redcap/api/
study_tracker:
  development:
    cohorts: https://studytracker-staging.fsm.northwestern.edu/research_roster/api/v1/cohorts
    generate_token: https://studytracker-staging.fsm.northwestern.edu/api/generate_token
    register: https://studytracker-staging.fsm.northwestern.edu/api/v1/subjects/:id.json
    empi_lookup: https://studytracker-staging.fsm.northwestern.edu/api/v2/empi_lookup.json
    verify_ssl: false
  test:
    cohorts: https://studytracker-staging.fsm.northwestern.edu/research_roster/api/v1/cohorts
    generate_token: https://studytracker-staging.fsm.northwestern.edu/api/generate_token
    register: http://enotis.dev/api/v1/subjects/:id.json
    empi_lookup: http://enotis.dev/api/v2/empi_lookup.json
    verify_ssl: false
  staging:
    cohorts: https://studytracker-staging.fsm.northwestern.edu/research_roster/api/v1/cohorts
    generate_token: https://studytracker-staging.fsm.northwestern.edu/api/generate_token
    register: https://studytracker-staging.fsm.northwestern.edu/api/v1/subjects/:id.json
    empi_lookup: https://studytracker-staging.fsm.northwestern.edu/api/v2/empi_lookup.json
  production:
    cohorts: https://studytracker.fsm.northwestern.edu/research_roster/api/v1/cohorts
    generate_token: https://studytracker.fsm.northwestern.edu/api/generate_token
    register: https://enotis.northwestern.edu/api/v1/subjects/:id.json
    empi_lookup: https://enotis.northwestern.edu/api/v2/empi_lookup.json
health_pro:
  development_stable:
    awardee: ILLINOIS
    project: all-of-us-rdr-stable
    project_id: all-of-us-ops-data-api-stable
    service_account: awardee-illinois@all-of-us-ops-data-api-stable.iam.gserviceaccount.com
    participant_summary_url: https://#{project}.appspot.com/rdr/v1/ParticipantSummary
    json_key_io: /Users/mjg994/ops-data-service/gcloud_key.json
    json_key_io_path: /Users/mjg994/ops-data-service/
    verify_ssl: false
  development:
    awardee: ILLINOIS
    project: all-of-us-rdr-prod
    project_id: all-of-us-ops-data-api-prod
    service_account: awardee-illinois@all-of-us-ops-data-api-prod.iam.gserviceaccount.com
    participant_summary_url: https://#{project}.appspot.com/rdr/v1/ParticipantSummary
    json_key_io: /Users/mjg994/ops-data-service/gcloud_key.json
    json_key_io_path: /Users/mjg994/ops-data-service/
    verify_ssl: false
  test:
    awardee: ILLINOIS
    project: all-of-us-rdr-prod
    project_id: all-of-us-ops-data-api-prod
    service_account: awardee-illinois@all-of-us-ops-data-api-prod.iam.gserviceaccount.com
    participant_summary_url: https://#{project}.appspot.com/rdr/v1/ParticipantSummary
    json_key_io: /Users/mjg994/ops-data-service/gcloud_key_prod_new.json
    json_key_io_path: /Users/mjg994/ops-data-service/
    verify_ssl: false
  staging:
    awardee: ILLINOIS
    project: all-of-us-rdr-prod
    project_id: all-of-us-ops-data-api-prod
    service_account: awardee-illinois@all-of-us-ops-data-api-prod.iam.gserviceaccount.com
    participant_summary_url: https://#{project}.appspot.com/rdr/v1/ParticipantSummary
    json_key_io: /var/www/apps/all-of-us-helper/shared/gcloud_key.json
    json_key_io_path: /var/www/apps/all-of-us-helper/shared/
    verify_ssl: false
  production:
    awardee: ILLINOIS
    project: all-of-us-rdr-prod
    project_id: all-of-us-ops-data-api-prod
    service_account: awardee-illinois@all-of-us-ops-data-api-prod.iam.gserviceaccount.com
    participant_summary_url: https://#{project}.appspot.com/rdr/v1/ParticipantSummary
    json_key_io: /var/www/apps/all-of-us-helper/shared/gcloud_key.json
    json_key_io_path: /var/www/apps/all-of-us-helper/shared/
    verify_ssl: false